dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: node-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: antest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
